gui:
  language: 'ja'
  showIcons: true
  branchColors:
    'fix': 'green'
    'feature': 'cyan'
    'master': 'red'
  theme:
    lightTheme: false
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - blue # set to `default` to have no background colour
    selectedRangeBgColor:
      - blue
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
  commitLength:
    show: true
os:
  edit: 'nvim'
git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
customCommands:
  - key: "E"
    context: "files"
    description: 'Add empty commit'
    loadingText: 'Committing empty commit...'
    command: "git commit --allow-empty -m {{index .PromptResponses 0 | quote}}"
    prompts:
      - type: "input"
        title: "Empty commit message"
        initialValue: ""
