gui:
  language: 'ja'
  showIcons: true
  branchColors:
    'fix': 'green'
    'feature': 'cyan'
    'master': 'red'
  theme:
    lightTheme: true
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - gray
os:
  editCommand: 'nvim'
git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
