[[plugins]] # plugin manager
repo        = 'Shougo/dein.vim'

[[plugins]] # neovim help jp
repo        = 'nekowasabi/nvimdoc-ja'

[[plugins]] # file tree
repo        = 'preservim/nerdtree'
hook_add = '''
  map <C-e> :NERDTreeToggle<CR>
  let NERDTreeShowHidden = 1
  let g:NERDTreeDirArrows = 1
'''

[[plugins]] # NERTDTree syntax
repo        = 'tiagofumo/vim-nerdtree-syntax-highlight'

[[plugins]] # icon install
repo        = 'ryanoasis/vim-devicons'
hook_add = '''
  let g:webdevicons_enable_nerdtree = 1
  let g:WebDevIconsNerdTreeAfterGlyphPadding = '   '
'''

[[plugins]] # 機能拡張環境
repo        = 'neoclide/coc.nvim'
